version: '3.4'

networks:
  docker-api-dev:
    driver: bridge

services:
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - EQ_FIRSTRUN_ADMINPASSWORDHASH="$PH"
    ports:
      - 8082:80
      - 5341:5341
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/data/postgres
volumes:
  postgres-db:
    driver: local
