# This workflow will build and test a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test .NET

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: Version of dotnet to use
        type: string
        default: 6
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
      project-folder:
        description: The folder containing the project to build
        type: string
        default: .

jobs:
  build-and-test:
    name: Build and Test .NET
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        working-directory: ${{ inputs.project-folder }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore /p:TreatWarningsAsErrors="true"

    - name: Test
      run: dotnet test --no-build --verbosity normal
