# This workflow will build and test a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Publish

jobs:
  build-and-test:
    name: Build and Test
    uses: .github/workflows/build-and-test.yml
    with:
      runs-on: ubuntu-latest
      project-folder: ./src
    on:
      push:
        branches: [ "main" ]
      pull_request:
        branches: [ "main" ]
  docker-publish:
    needs: [build-and-test]
    name: Build and Publish Docker image
    uses: .github/workflows/docker-publish.yml
    with:
      runs-on: ubuntu-latest
      context-path: ./src
    on:
      push:
        branches: [ "main" ]