name: Build, Test and Publish

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      runs-on: ubuntu-latest
      project-folder: ./src
  docker-publish-ghcr:
    needs: [build-and-test]
    uses: ./.github/workflows/ghcr-publish.yml
    with:
      runs-on: ubuntu-latest
      context-path: ./src
    secrets: inherit